# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_team_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='flockclient',
            name='default_channel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flockclient',
            name='team_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
