# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugapp', '0002_auto_20170723_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='group_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
