# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugapp', '0003_newticket_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='customer_query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
